### ISSUE TITLE
Normalize button

### ISSUE THREAD

**Issue by issamansur** [cr2007/links.hwtech.club#5]
Hi, I’ve been following your project. And I have a little proposition: in the any file (style css) add rule:
<code><pre>.button-body{
  min-width:  172px;
}
.column.is-2{
  min-width: 25%;
}
</pre></code>
Because of this condition, when the screen width is reduced, the buttons behave unnaturally. Send screens.
Site: https://hwtech.club/

![изображение](https://user-images.githubusercontent.com/77580844/133909723-79f51d07-3f4e-4b0b-88bf-21aa737b4da9.png)
![изображение](https://user-images.githubusercontent.com/77580844/133909729-92971114-8740-43d1-8d01-a68aebcc949b.png)

For example:

![изображение](https://user-images.githubusercontent.com/77580844/133910022-9b976520-6adf-4ade-84f8-6841dd50348f.png)
![изображение](https://user-images.githubusercontent.com/77580844/133910025-0c15fbab-29e3-4eca-ae1b-79268dc7edad.png)
![изображение](https://user-images.githubusercontent.com/77580844/133910026-cf0efcc8-74f3-47db-9aa8-a260c760cf0d.png)

**Comment by cr2007** [comment]
Hey @issamansur ,

Thanks for bringing up this issue.
Unfortunately, this is the repo for [links.hwtech.club](http://links.hwtech.club/)

Here's the place for the **[right repo](https://github.com/HWTechClub/hwtech.club/issues)**.
You can put this issue there and I'm sure we can help you out 😄 

~[CSK](https://github.com/cr2007)
